# Add configuration values here, as shown below.
#
 PUSHER_APP_ID: "662404"
 PUSHER_KEY: 73c4ff304f5f82cf2f94
 PUSHER_SECRET: 7b2974d6a8ad7a787a96
 PUSHER_CLUSTER: 'us2'
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
